//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.WanderingTurtle.ServiceClient.WanderingTurtleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WanderingTurtleService.IAccountingDetailsService")]
    public interface IAccountingDetailsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingDetailsService/GetAccountingDetails", ReplyAction="http://tempuri.org/IAccountingDetailsService/GetAccountingDetailsResponse")]
        com.WanderingTurtle.Common.AccountingDetails GetAccountingDetails(System.DateTime start, System.DateTime end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountingDetailsServiceChannel : com.WanderingTurtle.ServiceClient.WanderingTurtleService.IAccountingDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingDetailsServiceClient : System.ServiceModel.ClientBase<com.WanderingTurtle.ServiceClient.WanderingTurtleService.IAccountingDetailsService>, com.WanderingTurtle.ServiceClient.WanderingTurtleService.IAccountingDetailsService {
        
        public AccountingDetailsServiceClient() {
        }
        
        public AccountingDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public com.WanderingTurtle.Common.AccountingDetails GetAccountingDetails(System.DateTime start, System.DateTime end) {
            return base.Channel.GetAccountingDetails(start, end);
        }
    }
}
